M.Talha Ramzan
---
2330-0141
---
BS Ai
---
lab 09


1. Create a 1D array of 20 random integers between 1 and 100.

In [3]:
import numpy as np

arr = np.random.randint(1, 101, size=20)
print(arr)


[77 21 83 80 34 44 77 98 41 34 98 52 85 56 81 80 20 13 78 45]


2. Reshape the above array into a 4x5 matrix.

In [5]:
matrix = arr.reshape(4, 5)

print(matrix)


[[23 49 22 54 51]
 [98 47 61 73 36]
 [83 47 48 33 82]
 [29 32 44 22 73]]


3. Extract the diagonal elements of a 4x4 identity matrix.

In [21]:
import numpy as np
I = np.eye(4)
print("\n ", I)
diag_elements = np.diag(I)

print("\n \n Diagonal elements:\n" ,diag_elements)



  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 
 Diagonal elements:
 [1. 1. 1. 1.]


4. Create a 2D array of shape (5, 5) with random integers between 0 and 9, and replace all even
values with -1.

In [9]:
import numpy as np
arr = np.random.randint(0, 10, size=(5, 5))

arr[arr % 2 == 0] = -1

print(arr)


[[ 1 -1  7 -1 -1]
 [-1  9 -1  5 -1]
 [ 9 -1 -1  3  3]
 [-1 -1  5  5  9]
 [ 1  1  7 -1  7]]


5. Given two arrays a and b, find the common elements between them.

In [10]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

common_elements = np.intersect1d(a, b)

print(common_elements)


[3 4 5]


6. Calculate the matrix product of a 3x4 matrix and a 4x2 matrix.

In [13]:
import numpy as np

A = np.random.randint(1, 10, size=(3, 4))

B = np.random.randint(1, 10, size=(4, 2))

C = A @ B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Product C:\n", C)


Matrix A:
 [[5 3 5 6]
 [3 5 1 3]
 [2 2 9 5]]
Matrix B:
 [[3 8]
 [7 7]
 [2 6]
 [9 8]]
Matrix Product C:
 [[100 139]
 [ 73  89]
 [ 83 124]]


7. Create a 1D array of 500 random values between 0 and 1.

In [14]:
import numpy as np

arr = np.random.rand(500)

print(arr)


[0.97959566 0.3396689  0.46705041 0.07343893 0.89423996 0.30764948
 0.15699934 0.78081888 0.77078077 0.50983381 0.40137711 0.19454441
 0.22839586 0.39517458 0.38694489 0.81923861 0.56475348 0.69977504
 0.06554386 0.41854647 0.56989318 0.85691005 0.36954143 0.31983156
 0.38115539 0.40137925 0.09705112 0.84651421 0.33520599 0.66285154
 0.88144153 0.63380116 0.74381404 0.02746737 0.76069256 0.88528817
 0.5781846  0.8889476  0.53581568 0.85890524 0.47283075 0.4922292
 0.73941037 0.67994268 0.82592495 0.19080969 0.27847586 0.83690447
 0.03541643 0.9716268  0.99681989 0.99162648 0.96894368 0.1086819
 0.90658977 0.99801939 0.79092533 0.46816728 0.17688233 0.6549391
 0.01008827 0.54085117 0.55991229 0.25352127 0.7532002  0.24420505
 0.36448949 0.95536896 0.39421369 0.92492579 0.73517394 0.21676125
 0.57680043 0.82863945 0.12400998 0.92523671 0.68893375 0.95181153
 0.56972566 0.51655697 0.64310194 0.68662554 0.93818524 0.62710849
 0.47650423 0.47626561 0.23275926 0.95703139 0.54687291 0.5194108

8. Generate a 10x10 identity matrix.

In [15]:
import numpy as np

I = np.eye(10)

print(I)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


9. Use numpy to shuffle the rows randomly in above task.

In [16]:
import numpy as np

I = np.eye(10)

np.random.shuffle(I)

print(I)


[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


10. Generate an array of 10 random integers between 50 and 150 using Numpy. Find the minimum,
maximum, and the sum of the elements in the array.

In [17]:
import numpy as np

arr = np.random.randint(50, 151, size=10)

min_val = arr.min()

max_val = arr.max()

sum_val = arr.sum()

print("Array:", arr)
print("Minimum:", min_val)
print("Maximum:", max_val)
print("Sum:", sum_val)


Array: [113  65 145 133  61  90 109  59  54  51]
Minimum: 51
Maximum: 145
Sum: 880
