In [2]:
import numpy as np

start = float(input("Enter start value: "))
stop = float(input("Enter stop value: "))
size = int(input("Enter matrix size: "))

diagonal_values = np.linspace(start, stop, size)

diagonal_matrix = np.diag(diagonal_values)

print("\nDiagonal Matrix:")
print(diagonal_matrix)


Enter start value: 2
Enter stop value: 10
Enter matrix size: 5

Diagonal Matrix:
[[ 2.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.]
 [ 0.  0.  0.  8.  0.]
 [ 0.  0.  0.  0. 10.]]
