In [10]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [88, 76, 92],
    [70, 80, 65],
    [90, 95, 88],
    [60, 72, 75]
])

weights = np.array([
    [0.3],
    [0.4],
    [0.3]
])

final_scores = np.dot(marks, weights)

combined_matrix = np.vstack((marks.T, final_scores.T))

bonus_scores = final_scores * 1.05

np.savetxt("marks.txt", marks, fmt="%d")
np.savetxt("final_scores.txt", final_scores, fmt="%.2f")
np.savetxt("combined_matrix.txt", combined_matrix, fmt="%.2f")
np.savetxt("bonus_scores.txt", bonus_scores, fmt="%.2f")


print("Marks Matrix:\n", marks)
print("\nFinal Scores:\n", final_scores)
print("\nCombined Matrix:\n", combined_matrix)
print("\nBonus Scores:\n", bonus_scores)


Marks Matrix:
 [[78 85 90]
 [88 76 92]
 [70 80 65]
 [90 95 88]
 [60 72 75]]

Final Scores:
 [[84.4]
 [84.4]
 [72.5]
 [91.4]
 [69.3]]

Combined Matrix:
 [[78.  88.  70.  90.  60. ]
 [85.  76.  80.  95.  72. ]
 [90.  92.  65.  88.  75. ]
 [84.4 84.4 72.5 91.4 69.3]]

Bonus Scores:
 [[88.62 ]
 [88.62 ]
 [76.125]
 [95.97 ]
 [72.765]]
